### PR TITLE
Add textfiles.com

### LINKED ISSUE #155: textfiles.com
I'm interested in adding [textfiles.com](http://textfiles.com/) to the archive. Jason Scott is an incredible archivist, and textfiles.com is arguably one of his seminal "saves". There is so much early internet/BBS lore in those files. I've created a mirror of the site, and will submit a PR shortly.

### PR DESCRIPTION
**Pull request by brannondorsey**
Resolves #155. I've pinned the hash and will continue to "seed" for the foreseeable future.

### CODE REVIEW

**Comment by eminence** [comment]
Can you share the script you used to add this data into IPFS?  And can you clarify the license for this data

**Comment by brannondorsey** [comment]
Content was mirrored with a simple `wget` mirror process:

```
wget --mirror --convert-links --adjust-extension --page-requisites --no-parent -N http://textfiles.com
```
I'm having trouble finding specific info about the licensing of these files. Most all of them were openly shared on BBS between 1980-1995. [Here](http://textfiles.com/directory.html) is an info page about the documents. I will reach out to Jason Scott with this inquiry.

**Comment by brannondorsey** [comment]
It seems that the license info for textfiles is rather ambiguous. Like I said above, almost the entirety of the content was distributed around BBS between 20 to 35 years ago. Is this something that the IPFS archive community would be comfortable with archiving?

**Comment by lgierth** [comment]
Let's go for it :+1: 

Thanks :):)

**Comment by brannondorsey** [comment]
Woohoo, cheers mate!

**Pull request merged**
